print("Example 1.")
print("NAME :- Kalp Shah")
print("Address :- Ahmedabad")
print("\n")
print("Example 2.")
print("_________________\n")
print("|\t\t|")
print("|\t\t|")
print("|\t\t|")
print("|\t\t|\n")
print("-----------------\n")

print("Example 3.")
print("\t/\\")
print("\t/ \\")
print("_________________\n")
print("|\t\t|")
print("|\t\t|")
print("|\t\t|")
print("|\t\t|\n")
print("-----------------\n")

print("Example 4.")
print (" /\\ \n / \\ \n /  \\ \n /   \\ \n /    \\ ")print(" -------- \n !\t! \n !\t! \n !\t! \n !\t! \n -------- ")
input()
